# Generated by Django 4.0 on 2022-03-02 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(900), django.core.validators.MaxValueValidator(999)], verbose_name='Код оператора мобильной связи'),
        ),
    ]
