# Generated by Django 4.0 on 2022-03-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_client_mobile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mobile_codes',
            field=models.CharField(blank=True, help_text='укажите коды операторов для рассылки через \n        запятую или оставьте поле пустым для рассылки на все номера', max_length=512, verbose_name='Коды операторов'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='tags',
            field=models.CharField(blank=True, help_text='укажите тэги клиентов для рассылки через \n        запятую или оставьте поле пустым для рассылки всем клиентам', max_length=512, verbose_name='Тэги'),
        ),
    ]
