# Generated by Django 4.0 on 2022-03-02 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_mailing_mobile_codes_mailing_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(599)], verbose_name='Статус отправки'),
        ),
    ]
